name: Build Docker Container for Arm32

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t arm32-hello .

      - name: Save Docker image as tarball
        run: docker save arm32-hello -o arm32-hello.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: arm32-hello-image
          path: arm32-hello.tar
